// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9lQBZJdixX4hGxqfIRn4bwrsM_KHhIRU',
    appId: '1:159393059456:web:d264d322cb8600cb81cc65',
    messagingSenderId: '159393059456',
    projectId: 'attendance-app-275ee',
    authDomain: 'attendance-app-275ee.firebaseapp.com',
    storageBucket: 'attendance-app-275ee.firebasestorage.app',
    measurementId: 'G-6QZXB69PL2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhvAqpwVa8nHPjnCsqzAeCwa9QAkrosag',
    appId: '1:159393059456:android:df6e5a2cc7cd88b781cc65',
    messagingSenderId: '159393059456',
    projectId: 'attendance-app-275ee',
    storageBucket: 'attendance-app-275ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3cz8gl5_IDCt7FRSq9Fr9ctnCsSdckcE',
    appId: '1:159393059456:ios:f9d23bfba0ac2ddd81cc65',
    messagingSenderId: '159393059456',
    projectId: 'attendance-app-275ee',
    storageBucket: 'attendance-app-275ee.firebasestorage.app',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3cz8gl5_IDCt7FRSq9Fr9ctnCsSdckcE',
    appId: '1:159393059456:ios:f9d23bfba0ac2ddd81cc65',
    messagingSenderId: '159393059456',
    projectId: 'attendance-app-275ee',
    storageBucket: 'attendance-app-275ee.firebasestorage.app',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9lQBZJdixX4hGxqfIRn4bwrsM_KHhIRU',
    appId: '1:159393059456:web:915fd7911fe9b9a781cc65',
    messagingSenderId: '159393059456',
    projectId: 'attendance-app-275ee',
    authDomain: 'attendance-app-275ee.firebaseapp.com',
    storageBucket: 'attendance-app-275ee.firebasestorage.app',
    measurementId: 'G-XTMRN98VPQ',
  );
}
